apiVersion: v1
kind: Service
metadata:
  name: auth-middleware
  namespace: confuse
  labels:
    app: auth-middleware
    service: auth
spec:
  type: ClusterIP
  selector:
    app: auth-middleware
  ports:
  - name: http
    port: 3010
    targetPort: 3010
    protocol: TCP
  - name: grpc
    port: 50058
    targetPort: 50058
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-middleware-grpc
  namespace: confuse
  labels:
    app: auth-middleware
    service: auth
spec:
  type: ClusterIP
  selector:
    app: auth-middleware
  ports:
  - name: grpc
    port: 50058
    targetPort: 50058
    protocol: TCP
